# Generated by Django 3.2.9 on 2022-03-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wordle_game', '0002_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new',
            new_name='new1',
        ),
    ]
