# Generated by Django 3.2.9 on 2022-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wordle_game', '0003_rename_new_new1'),
    ]

    operations = [
        migrations.CreateModel(
            name='new2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='new1',
        ),
    ]
