# Generated by Django 3.2.9 on 2022-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wordle_game', '0004_auto_20220317_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='newtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Int', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='new2',
        ),
    ]
