# Generated by Django 3.2.9 on 2022-03-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wordle_game', '0008_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
        migrations.DeleteModel(
            name='words',
        ),
    ]
