# Generated by Django 3.2.7 on 2022-05-31 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wordle_game', '0010_new_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='Word',
            new_name='word',
        ),
    ]
