# Generated by Django 3.2.7 on 2022-05-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wordle_game', '0011_rename_word_words_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='words',
            new_name='Word',
        ),
    ]
